language: go

sudo: required

services:
  - docker

go_import_path: github.com/gaocegege/maintainer

go:
  - 1.8

script: 
  - go install .
  - maintainer --help

after_script: 
  - ./scripts/build-for-alpine.sh
  - docker build -t gaocegege/maintainer .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push gaocegege/maintainer
