language: go

sudo: required

services:
  - docker

go_import_path: github.com/gaocegege/maintainer

go:
  - 1.8

script: 
  - go install .
  - maintainer --help

after_script: 
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/master-build-in-travis.sh; fi'
